Import("env")

import subprocess
from pathlib import Path


DEFAULT_VERSION = "0.0.0-dev"


def _run_git(args, cwd):
    return subprocess.check_output(["git", *args], cwd=cwd, text=True).strip()


def resolve_fw_version(project_dir):
    try:
        tag = _run_git(["describe", "--tags", "--abbrev=0"], project_dir)
        if tag:
            return tag
    except Exception:
        pass
    return DEFAULT_VERSION


project_dir = Path(env.subst("$PROJECT_DIR"))
fw_version = resolve_fw_version(project_dir)

print(f"[fw-version] FW_VERSION={fw_version}")

header_path = project_dir / "include" / "fw_version_auto.h"
header_content = (
    "#pragma once\n"
    "\n"
    "// Auto-generated by scripts/fw_version_from_git.py\n"
    f"#define FW_VERSION \"{fw_version}\"\n"
)

header_path.write_text(header_content, encoding="utf-8")
